CREATE TABLE mf_keny_alldata (
    id INT AUTO_INCREMENT PRIMARY KEY,
    document_detail_id INT,
    amc_id INT,
    amc_name TEXT,
    MainScheme_ID INT,
    main_scheme_name TEXT,
    fund_id INT,
    fund_name TEXT,
    scheme_objective TEXT,
    suitable_for_investors TEXT,
    benchmark_index_id INT,
    benchmark_index TEXT,
    min_addl_amt VARCHAR(100),
    min_addl_amt_multiple VARCHAR(100),
    min_amt VARCHAR(100),
    min_amt_multiple VARCHAR(100),
    monthly_aaum_date VARCHAR(200),
    monthly_aaum_value VARCHAR(255),
    scheme_launch_date TEXT,
    ytm VARCHAR(100),
    port_turnover_ratio VARCHAR(100),
    mod_duration VARCHAR(100),
    avg_maturity VARCHAR(100),
    macaulay VARCHAR(100),
    sharpe VARCHAR(100),
    std_dev VARCHAR(100),
    beta VARCHAR(100),
    tracking_error VARCHAR(100),
    r_squared_ratio VARCHAR(100),
    average_div_yield VARCHAR(100),
    average_pb VARCHAR(100),
    average_pe VARCHAR(100),
    alpha VARCHAR(100),
    treynor_ratio VARCHAR(100),
    information_ratio VARCHAR(100),
    sortino_ratio VARCHAR(100),
    arithmetic_mean_ratio VARCHAR(100),
    correlation_ratio VARCHAR(100),
    roe_ratio VARCHAR(100),
    downside_deviation VARCHAR(100),
    upside_deviation VARCHAR(100),
    price_per_unit VARCHAR(100),
    creation_unit_size VARCHAR(100),
    offer_price VARCHAR(100),
    min_target_amt VARCHAR(100),
    entered_user TEXT,
    entered_date TIMESTAMP,
    modified_user TEXT,
    modified_date TIMESTAMP,
    is_migrated TINYINT,
    is_valid TINYINT,
    close_date TEXT,
    open_date TEXT,
    face_value TEXT,
    type_of_scheme TEXT,
    Riskometer TEXT,
    Riskometer_benchmark TEXT,
    SchemeCategory_level2_ID INT,
    scheme_code TEXT,
    sai_weblink TEXT,
    nfo_min_sub_amt DECIMAL(10,0),
    amc_for_month VARCHAR(50),
    entered_time VARCHAR(60)
);


CREATE TABLE mf_keny_fund_manager (
    id INT AUTO_INCREMENT PRIMARY KEY,
    document_detail_id INT,
    MainScheme_ID INT,
    main_scheme_name TEXT,
    name VARCHAR(100),
    managing_fund_since VARCHAR(100),
    qualification TEXT,
    total_experience TEXT,
    entered_user VARCHAR(100),
    entered_date TIMESTAMP,
    modified_user VARCHAR(100),
    modified_date TIMESTAMP,
    is_migrated TINYINT,
    amc_for_month VARCHAR(50),
    entered_time VARCHAR(60)
);
