CREATE TABLE mf_common_fund_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    entered_time VARCHAR(40),
    amc_for_month VARCHAR(40),
    data_from VARCHAR(100),
	amc_name TEXT,
    main_scheme_name TEXT,
    mutual_fund_name TEXT,
	benchmark_index TEXT,
    monthly_aaum_date VARCHAR(50),
    monthly_aaum_value TEXT,
    scheme_launch_date TEXT,
    min_addl_amt VARCHAR(150),
    min_addl_amt_multiple VARCHAR(150),
    min_amt VARCHAR(150),
    min_amt_multiple VARCHAR(150),
    entry_load TEXT,
    exit_load TEXT,
    alpha VARCHAR(140),  
    arithmetic_mean_ratio VARCHAR(140),  
    average_div_yld VARCHAR(140),  
    average_pb VARCHAR(140),  
    average_pe VARCHAR(140),  
    avg_maturity VARCHAR(140),  
    beta VARCHAR(140),  
    correlation_ratio VARCHAR(140),  
    downside_deviation VARCHAR(140),  
    information_ratio VARCHAR(140),  
    macaulay VARCHAR(140),  
    mod_duration VARCHAR(140),  
    port_turnover_ratio VARCHAR(140),  
    r_squared_ratio VARCHAR(140),  
    roe_ratio VARCHAR(140),  
    sharpe VARCHAR(140),  
    sortino_ratio VARCHAR(140),  
    std_dev VARCHAR(140),
    tracking_error VARCHAR(140),  
    treynor_ratio VARCHAR(140),  
    upside_deviation VARCHAR(140),  
    ytm VARCHAR(140)
);


CREATE TABLE mf_fund_manager_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mutual_fund_id INT,
    entered_time VARCHAR(40),
    amc_for_month VARCHAR(40),
    data_from VARCHAR(100),
	amc_name TEXT,
    mutual_fund_name TEXT,
    main_scheme_name TEXT,
    name TEXT,
    qualification TEXT,
    managing_fund_since TEXT,
    total_exp TEXT,
    FOREIGN KEY (mutual_fund_id) REFERENCES mf_common_fund_data(id) ON DELETE CASCADE
);
